name: "urbanflow"
version: "1.0.0"
config-version: 2

profile: "urbanflow"
require-dbt-version: [">=1.9.0", "<1.10.0"]

model-paths: ["models"]
test-paths: ["tests"]
packages-install-path: "dbt_packages"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  urbanflow:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: view
