-- UrbanFlow Phase 7 analytical, landing, and audit tables.
-- Run as a role with the existing URBANFLOW schema privileges.
-- This script does not create users, roles, warehouses, stages, or Azure resources.

USE DATABASE URBANFLOW;

CREATE TABLE IF NOT EXISTS ANALYTICS.FACT_TRIPS (
  TRIP_ID VARCHAR NOT NULL, VENDOR_ID NUMBER(10,0),
  PICKUP_DATETIME TIMESTAMP_NTZ NOT NULL, DROPOFF_DATETIME TIMESTAMP_NTZ NOT NULL,
  PICKUP_DATE_KEY NUMBER(10,0) NOT NULL, DROPOFF_DATE_KEY NUMBER(10,0) NOT NULL,
  PICKUP_TIME_KEY NUMBER(10,0) NOT NULL, DROPOFF_TIME_KEY NUMBER(10,0) NOT NULL,
  PICKUP_LOCATION_ID NUMBER(10,0) NOT NULL, DROPOFF_LOCATION_ID NUMBER(10,0) NOT NULL,
  PASSENGER_COUNT NUMBER(10,2), TRIP_DISTANCE FLOAT, RATE_CODE_ID NUMBER(10,0),
  PAYMENT_TYPE NUMBER(10,0), STORE_AND_FORWARD_FLAG VARCHAR,
  FARE_AMOUNT NUMBER(18,2), EXTRA NUMBER(18,2), MTA_TAX NUMBER(18,2),
  TIP_AMOUNT NUMBER(18,2), TOLLS_AMOUNT NUMBER(18,2),
  IMPROVEMENT_SURCHARGE NUMBER(18,2), CONGESTION_SURCHARGE NUMBER(18,2),
  AIRPORT_FEE NUMBER(18,2), CBD_CONGESTION_FEE NUMBER(18,2), TOTAL_AMOUNT NUMBER(18,2),
  TRIP_DURATION_MINUTES FLOAT, AVERAGE_SPEED_MPH FLOAT, FARE_PER_MILE FLOAT,
  TIP_PERCENTAGE FLOAT, IS_FINANCIAL_ADJUSTMENT BOOLEAN NOT NULL,
  NON_ADJUSTMENT_REVENUE NUMBER(18,2), FINANCIAL_ADJUSTMENT_AMOUNT NUMBER(18,2),
  SOURCE_YEAR NUMBER(10,0) NOT NULL, SOURCE_MONTH NUMBER(10,0) NOT NULL,
  SOURCE_FILE VARCHAR, INGESTED_AT_UTC TIMESTAMP_NTZ, BRONZE_RUN_ID VARCHAR,
  SILVER_RUN_ID VARCHAR, SILVER_PROCESSED_AT_UTC TIMESTAMP_NTZ,
  GOLD_RUN_ID VARCHAR NOT NULL, GOLD_PROCESSED_AT_UTC TIMESTAMP_NTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS ANALYTICS.DIM_DATE (
  DATE_KEY NUMBER(10,0) NOT NULL, CALENDAR_DATE DATE NOT NULL, YEAR NUMBER(10,0) NOT NULL,
  QUARTER NUMBER(10,0) NOT NULL, MONTH NUMBER(10,0) NOT NULL, MONTH_NAME VARCHAR NOT NULL,
  WEEK NUMBER(10,0) NOT NULL, DAY NUMBER(10,0) NOT NULL, DAY_OF_WEEK NUMBER(10,0) NOT NULL,
  DAY_NAME VARCHAR NOT NULL, IS_WEEKEND BOOLEAN NOT NULL, GOLD_RUN_ID VARCHAR NOT NULL,
  GOLD_PROCESSED_AT_UTC TIMESTAMP_NTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS ANALYTICS.DIM_TIME (
  TIME_KEY NUMBER(10,0) NOT NULL, HOUR NUMBER(10,0) NOT NULL, MINUTE NUMBER(10,0) NOT NULL,
  HOUR_BUCKET VARCHAR NOT NULL, AM_PM VARCHAR NOT NULL, TIME_OF_DAY VARCHAR NOT NULL,
  GOLD_RUN_ID VARCHAR NOT NULL, GOLD_PROCESSED_AT_UTC TIMESTAMP_NTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS ANALYTICS.DIM_LOCATION (
  LOCATION_ID NUMBER(10,0) NOT NULL, BOROUGH VARCHAR, ZONE VARCHAR, SERVICE_ZONE VARCHAR,
  BOROUGH_NORMALIZED VARCHAR, ZONE_NORMALIZED VARCHAR, SOURCE_FILE VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ, BRONZE_RUN_ID VARCHAR, SILVER_RUN_ID VARCHAR,
  SILVER_PROCESSED_AT_UTC TIMESTAMP_NTZ, GOLD_RUN_ID VARCHAR NOT NULL,
  GOLD_PROCESSED_AT_UTC TIMESTAMP_NTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS ANALYTICS.AGG_DAILY_TRIPS (
  SOURCE_YEAR NUMBER(10,0) NOT NULL, SOURCE_MONTH NUMBER(10,0) NOT NULL,
  PICKUP_DATE_KEY NUMBER(10,0) NOT NULL, TRIP_COUNT NUMBER(19,0) NOT NULL,
  TOTAL_REVENUE NUMBER(28,2), AVERAGE_FARE NUMBER(18,2), AVERAGE_TOTAL_AMOUNT NUMBER(18,2),
  AVERAGE_TRIP_DISTANCE FLOAT, TOTAL_DISTANCE FLOAT, AVERAGE_PASSENGER_COUNT NUMBER(18,2),
  TIP_REVENUE NUMBER(28,2), TOLL_REVENUE NUMBER(28,2), NON_ADJUSTMENT_REVENUE NUMBER(28,2),
  FINANCIAL_ADJUSTMENT_COUNT NUMBER(19,0) NOT NULL,
  FINANCIAL_ADJUSTMENT_AMOUNT NUMBER(28,2), GOLD_RUN_ID VARCHAR NOT NULL,
  GOLD_PROCESSED_AT_UTC TIMESTAMP_NTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS ANALYTICS.AGG_LOCATION_TRIPS (
  SOURCE_YEAR NUMBER(10,0) NOT NULL, SOURCE_MONTH NUMBER(10,0) NOT NULL,
  LOCATION_ID NUMBER(10,0) NOT NULL, BOROUGH VARCHAR, ZONE VARCHAR,
  PICKUP_TRIP_COUNT NUMBER(19,0) NOT NULL, DROPOFF_TRIP_COUNT NUMBER(19,0) NOT NULL,
  TOTAL_REVENUE NUMBER(28,2), AVERAGE_TRIP_DISTANCE FLOAT,
  AVERAGE_TOTAL_AMOUNT NUMBER(18,2), TOTAL_DISTANCE FLOAT, GOLD_RUN_ID VARCHAR NOT NULL,
  GOLD_PROCESSED_AT_UTC TIMESTAMP_NTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS ANALYTICS.AGG_HOURLY_TRIPS (
  SOURCE_YEAR NUMBER(10,0) NOT NULL, SOURCE_MONTH NUMBER(10,0) NOT NULL,
  PICKUP_DATE_KEY NUMBER(10,0) NOT NULL, HOUR NUMBER(10,0) NOT NULL,
  HOUR_BUCKET VARCHAR NOT NULL, TIME_OF_DAY VARCHAR NOT NULL, TRIP_COUNT NUMBER(19,0) NOT NULL,
  TOTAL_REVENUE NUMBER(28,2), AVERAGE_TOTAL_AMOUNT NUMBER(18,2),
  AVERAGE_TRIP_DISTANCE FLOAT, TOTAL_DISTANCE FLOAT, GOLD_RUN_ID VARCHAR NOT NULL,
  GOLD_PROCESSED_AT_UTC TIMESTAMP_NTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS LANDING.FACT_TRIPS LIKE ANALYTICS.FACT_TRIPS;
CREATE TABLE IF NOT EXISTS LANDING.DIM_DATE LIKE ANALYTICS.DIM_DATE;
CREATE TABLE IF NOT EXISTS LANDING.DIM_TIME LIKE ANALYTICS.DIM_TIME;
CREATE TABLE IF NOT EXISTS LANDING.DIM_LOCATION LIKE ANALYTICS.DIM_LOCATION;
CREATE TABLE IF NOT EXISTS LANDING.AGG_DAILY_TRIPS LIKE ANALYTICS.AGG_DAILY_TRIPS;
CREATE TABLE IF NOT EXISTS LANDING.AGG_LOCATION_TRIPS LIKE ANALYTICS.AGG_LOCATION_TRIPS;
CREATE TABLE IF NOT EXISTS LANDING.AGG_HOURLY_TRIPS LIKE ANALYTICS.AGG_HOURLY_TRIPS;

CREATE TABLE IF NOT EXISTS AUDIT.LOAD_AUDIT (
  RUN_ID VARCHAR NOT NULL, DATASET VARCHAR NOT NULL,
  SOURCE_YEAR NUMBER(10,0), SOURCE_MONTH NUMBER(10,0),
  SOURCE_ROW_COUNT NUMBER(19,0), LANDING_ROW_COUNT NUMBER(19,0), TARGET_ROW_COUNT NUMBER(19,0),
  STATUS VARCHAR NOT NULL, STARTED_AT TIMESTAMP_TZ NOT NULL, COMPLETED_AT TIMESTAMP_TZ NOT NULL,
  ERROR_MESSAGE VARCHAR, RECONCILIATION_STATUS VARCHAR NOT NULL,
  IDEMPOTENCY_PASS NUMBER(10,0), IDEMPOTENCY_STATUS VARCHAR, SCHEMA_VERSION VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS AUDIT.RECONCILIATION_RESULTS (
  RUN_ID VARCHAR NOT NULL, DATASET VARCHAR NOT NULL, CHECK_NAME VARCHAR NOT NULL,
  METRIC_VALUE FLOAT NOT NULL, EXPECTED_VALUE FLOAT NOT NULL, STATUS VARCHAR NOT NULL,
  MEASURED_AT TIMESTAMP_TZ NOT NULL
);
